# Generated by Django 4.1.5 on 2023-01-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_grade_alter_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
