# Generated by Django 4.1.5 on 2023-01-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_assignment_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='attachment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='submitted_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
