# Generated by Django 4.1.5 on 2023-01-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_grade_course_grad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='grad',
            new_name='grade',
        ),
    ]
