# Generated by Django 4.1.5 on 2023-01-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_studentassignment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='is_submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
