# Generated by Django 4.1.5 on 2023-01-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_grade_course_classes_course_sum_assignments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.TimeField(),
        ),
    ]
