# Generated by Django 4.1.5 on 2023-01-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_studentassignment_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name=''),
        ),
    ]
