# Generated by Django 4.1.5 on 2023-01-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_studentassignment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='attachment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
