# Generated by Django 4.1.5 on 2023-01-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_studentassignment_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher',
            new_name='type',
        ),
    ]
