# Generated by Django 4.1.5 on 2023-01-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.TimeField(),
        ),
    ]
