# Generated by Django 4.1.5 on 2023-01-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='supervisor',
            new_name='type',
        ),
    ]
