# Generated by Django 4.1.5 on 2023-01-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
