# Generated by Django 4.1.5 on 2023-01-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assignment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
