# Generated by Django 4.1.5 on 2023-01-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_alter_assignment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name=''),
        ),
    ]
