# Generated by Django 4.1.5 on 2023-01-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_alter_assignment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
